# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "KubeEdge"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "2023 &copy; KubeEdge Project Authors. All rights reserved."

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-137983920-1"

# Enable comments by entering your Disqus shortname
disqusShortname = "kubeedge"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = true

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"


[params]
# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Versions"

[[params.versions]]
fullversion = "v1.12"
version = "v1.12"
githubbranch = "v1.12"
docsbranch = "master"
url = "https://kubeedge.io/en/"

[[params.versions]]
fullversion = "v1.11"
version = "v1.11"
githubbranch = "v1.11"
docsbranch = "release-1.11"
url = "https://v1-11.docs.kubeedge.io/en/"

[[params.versions]]
fullversion = "v1.10"
version = "v1.10"
githubbranch = "v1.10"
docsbranch = "release-1.10"
url = "https://v1-10.docs.kubeedge.io/en/"

[[params.versions]]
fullversion = "v1.9"
version = "v1.9"
githubbranch = "v1.9"
docsbranch = "release-1.9"
url = "https://v1-9.docs.kubeedge.io/en/"

[[params.versions]]
fullversion = "v1.8"
version = "v1.8"
githubbranch = "v1.8"
docsbranch = "release-1.8"
url = "https://v1-8.docs.kubeedge.io/en/"
