# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"

#Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "KubeEdge一个支持边缘计算的开放平台"
  [zh.params]
    description = ""

  [[zh.menu.main]]
    name = "主页"
    url = "#home_slider"
    weight = 1


  [[zh.menu.main]]
    name = "文档"
    url = "https://docs.kubeedge.io"
    weight = 2

  [[zh.menu.main]]
    name = "博客"
    url = "blog/"
    weight = 3

  [[zh.menu.main]]
    name = "事件"
    url = "blog/"
    weight = 4

  [[zh.menu.main]]
    name = "Github"
    url = "https://github.com/kubeedge"
    weight = 5


  [[zh.menu.main]]
    name = "下载"
    url = "https://github.com/kubeedge/kubeedge/releases"
    weight = 6

  [[zh.menu.main]]
    name = "加入社区"
    url = "community/"
    parent = "社区"
    weight = 7

  [[zh.menu.main]]
    name = "合作伙伴"
    url = "partner/"
    parent = "社区"
    weight = 8

  [[zh.menu.main]]
    name = "案例研究"
    url = "study/"
    parent = "社区"
    weight = 9
  
  # Right Menu
[[zh.menu.main_right]]
  name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/kubeedge/kubeedge"
  weight = 10

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/KubeEdge"
  weight = 20

[[zh.menu.main_right]]
  name = "<i class=\"fab fa-slack\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://join.slack.com/t/kubeedge/shared_invite/enQtNjc0MTg2NTg2MTk0LWJmOTBmOGRkZWNhMTVkNGU1ZjkwNDY4MTY4YTAwNDAyMjRkMjdlMjIzYmMxODY1NGZjYzc4MWM5YmIxZjU1ZDI"
  weight = 30

# Documentation 

[[zh.menu.docs]]
  name = "欢迎"
  weight = 5
  identifier = "welcome"

[[zh.menu.docs]]
  name = "概念"
  weight = 10
  identifier = "concepts"

[[zh.menu.docs]]
  name = "建立"
  weight = 20
  identifier = "setup"

[[zh.menu.docs]]
  name = "指南"
  weight = 30
  identifier = "guides"

[[zh.menu.docs]]
  name = "常见问题"
  weight = 40
  identifier = "faq"


# [ko]
  # languageCode = "ko"
  # contentDir = "content/ko"
  # title = "KubeEdge"
  # [ko.params]
    # description = ""
  # [[ko.menu.main]]
  # name = "홈"
  # url = "#home_slider"
  # weight = 1
# 
  # [[ko.menu.main]]
  # name = "why KubeEdge"
  # url = "#why-kubeedge"
  # weight = 2
# 
  # [[ko.menu.main]]
  # name = "문서"
  # url = "https://docs.kubeedge.io"
  # weight = 3
# 
  # [[ko.menu.main]]
  # name = "블로그"
  # url = "blog/"
  # weight = 4
# 
  # [[ko.menu.main]]
  # name = "다운로드"
  # url = "https://github.com/kubeedge/kubeedge/releases"
  # weight = 5
# 
#   
  # # Right Menu
# [[ko.menu.main_right]]
  # name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  # post = ""
  # url = "https://github.com/kubeedge/kubeedge"
  # weight = 10
# 
# [[ko.menu.main_right]]
  # name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  # post = ""
  # url = "https://twitter.com/KubeEdge"
  # weight = 20
# 
# [[ko.menu.main_right]]
  # name = "<i class=\"fab fa-slack\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  # post = ""
  # url = "https://join.slack.com/t/kubeedge/shared_invite/enQtNjc0MTg2NTg2MTk0LWJmOTBmOGRkZWNhMTVkNGU1ZjkwNDY4MTY4YTAwNDAyMjRkMjdlMjIzYmMxODY1NGZjYzc4MWM5YmIxZjU1ZDI"
  # weight = 30
# 
# # Documentation 
# 
# [[ko.menu.docs]]
  # name = "환영"
  # weight = 5
  # identifier = "welcome"
# 
# [[ko.menu.docs]]
  # name = "개념"
  # weight = 10
  # identifier = "concepts"
# 
# [[ko.menu.docs]]
  # name = "설치"
  # weight = 20
  # identifier = "setup"
# 
# [[ko.menu.docs]]
  # name = "가이드"
  # weight = 30
  # identifier = "guides"
# 
# [[ko.menu.docs]]
  # name = "문의"
  # weight = 40
  # identifier = "faq"

  
  