[build]
publish = "public"
command = "hugo"
functions = "functions/"

[context.production.environment]
  HUGO_VERSION = "0.53"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.53"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.53"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.53"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/latestversion"
  to = "/.netlify/functions/latestversion"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://docs.kubeedge.io/*"
  to = "https://kubeedge.io/en/docs/:splat"
  status = 200
  force = true
