[build]
publish = "build"
command = "yarn build"
functions = "functions/"

[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_VERSION = "9.5.1"

[[redirects]]
  from = "/latestversion"
  to = "/.netlify/functions/latestversion"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://kubeedge.io/en"
  to = "https://kubeedge.io"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://edgemesh.kubeedge.io"
  to = "https://edgemesh.netlify.app"
  status = 200
  force = true

